### ISSUE TITLE
Possible boot bug with Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by cole-seph-work** [mapbox/lockbox#1]
Ubuntu 20.04 LTS has had no issues but it appears 20.04.2 LTS may be having boot failing issues when lockbox is used on a fresh installation of 20.04.2 LTS. 
Problem looks like this: 
![image](https://user-images.githubusercontent.com/53199598/124938546-61b24300-dfd6-11eb-8b28-66faf0213866.png)

We are looking into this

**Comment by cole-seph-work** [comment]
It appears this was a user-issue that originated from either using incorrect USB installer media or not properly encrypting the machine during the initial OS-install wizard. 
Tests with Ubuntu 20.04.2 LTS were successful. Adding this version to our supported versions in the readme.md

**Comment by cole-seph-work** [comment]
@deniskoronchik feel free to add anything here to help us with our understanding of the issue. Please bear in mind that this a public open source repo when sharing information. 
Otherwise, I will keep this issue closed

**Comment by deniskoronchik** [comment]
I've tried `nvidia-settings` ui. Didn't try all options, but switching of some options with UI doesn't cause the problem.
I assume that this one command cause the issue: `sudo nvidia-xconfig -a --cool-bits=28 --allow-empty-initial-configuration`
